### ISSUE TITLE
PS4 NOR dump Jasipi method.

### ISSUE THREAD

**Issue by SnakeEate** [SegFault42/SegFault42_lab#22]
Hey Man.
hope you're well.
I saw an old post where you tried to dump PS4's NOR chip using the Jasipi methodd. Just wanted to catch up. Were you able to do it with Raspierrby pi using the old version of Jasipi that you provided? 

https://gbatemp.net/threads/jaispi-error-ps4-dump-nor.549383/
Thanks,

**Comment by SegFault42** [comment]
Hey !
Yes it worked well !

![EGTfQ9OU8AEgWZ_](https://user-images.githubusercontent.com/9384676/214325116-9b2d506f-82b9-493a-8bc3-3a830c123126.jpg)

 I had to unsolder the nor

**Comment by SnakeEate** [comment]
> 

Thank you sharing! Good news.
I ordered a Raspberry Pi zero and will try this out. I think it should work with a zero too. 
Thanks again

**Comment by SegFault42** [comment]
Let me know if you need any help

**Comment by SnakeEate** [comment]
Hey Man. How's it going?
I finished the tough part and got stuck in the easy part. I'm using a Raspberry pi zero with no wifi. I'm SSh-ed to it via USB from my Mac. Now I don't know how to get Jaispi file into my Pi that has no internet access. I tried copying Jaspit into the SD boot folder but it did not show up on my Pi. I'd appreciate your help.

**Comment by SnakeEate** [comment]
![IMG_6075](https://user-images.githubusercontent.com/89381454/215832169-f120705e-e23d-47d6-9652-213c24ba0613.JPG)

Hi 
Got the error: 
root@raspberrypi:/home/pi# ./jaispi -r ps4pi.bin /home/pi
JaiSpi v1.0                                     Contact: jaicrab@jaicrab.org
Error opening device /home/pi...

Guessing it's soldering-related? what do you think?

**Comment by SegFault42** [comment]
Hey ! 

Where di you get the pinout documentation ? Can you send me a link ?

What kind of NOR it is ?

**Comment by SnakeEate** [comment]
> Hey !
> 
> Where di you get the pinout documentation ? Can you send me a link ?
>  I followed this: https://www.psdevwiki.com/ps4/JAISPI
> What kind of NOR it is ?
I dumped it earlier using Ch341A, and it showed this type:
<img width="606" alt="Sucess" src="https://user-images.githubusercontent.com/89381454/215842081-62b02b36-8eec-4d02-88e4-c4132654d2c2.png">

What's on your mind?

**Comment by SegFault42** [comment]
The right command shoudl be something like : ./jaispi -r ps4pi.bin /dev/{your_device}

To find the nor just unsolder the GND pin, exec ls -l /dev, resolder the GND pin, exec ls -l /dev and find the new device

then you will be able to dump the nor

with this command : `./jaispi -r ps4pi.bin /home/pi` You are giving the home folder to jaispi not the NOR located in /dev

**Comment by SnakeEate** [comment]
Hi. 
Thanks for your help, it turns out I'm getting this error because [SPI was not turned active on my PI.](https://www.mediafire.com/?6jcpwd7mzw6fnsk) I enabled it and was able to dump two identical files. This was a fun little experiment. Thanks again.

<img width="656" alt="Screen Shot 2023-01-31 at 9 43 34 PM" src="https://user-images.githubusercontent.com/89381454/215859979-9868a5b9-4b32-4520-9983-0dae2c9aa321.png">

**Comment by SegFault42** [comment]
Congrats !

Happy for you!

I close this issue !
